### ISSUE TITLE
Finish implementing the 'User profile' page and controller

### ISSUE THREAD

**Issue by nerminjukan** [nerminjukan/DiaGenKri#16]
Some functionality has already been added in the 'administration page - nermin' PR, continue solving this in a different branch.

**Comment by nerminjukan** [comment]
I've implemented the profile picture storing functionality, now I'm working on storing the textual information changes to the DB. The code might need some optimising after the majority of the project's main functionalities are working.

**Comment by dejvv** [comment]
Great! User's picture can be displayed at dropdown menu that contains user's informations, there is already reserved space for that in place where is some [glyphicon](https://getbootstrap.com/docs/3.3/components/#glyphicons) right now.
