### ISSUE TITLE
GDRP

### ISSUE THREAD

**Issue by nerminjukan** [nerminjukan/DiaGenKri#17]
The question is whether we have to implement (and how) the functionalities and requirements to satisfy the new GDRP standards for collecting and manipulating personal data?

**Comment by mmoskon** [comment]
Do we have any personal data in the database?

**Comment by nerminjukan** [comment]
One idea was to create a 'public user profile' so that users can connect between each other (or at least see their contact information). The database currently holds the name, surname and e-mail address (regarding personal data).

**Comment by mmoskon** [comment]
1) Add a checkbox: (by default unticked)
2) The consent has to be evident in the database: add additional property to each user (date of consent)
3) The system should allow each user to remove its consent (after which the user's account is deleted)

Question: 
How to specify the consent text/terms and conditions properly?
Example: I consent with the storage of my personal data. Your personal data will be used solely to administer your account. I have the right to withdraw my consent at any time (my personal data will be stored until the withdrawal of consent). 

https://www.yellowcherrydigital.co.uk/gdpr-and-user-consent/
https://www.econsultancy.com/blog/69256-gdpr-how-to-create-best-practice-privacy-notices-with-examples

**Comment by nerminjukan** [comment]
I've been informed, that the above method is completely suitable for our application and the nature of its personal information usage. Also, we should consider hashing the data in the DB. In case of a breach, if the data is not hashed, all the users must be informed of the breach. If the data is hashed, then it is considered that the breach did not compromise any personal information and no informing is necessary.
