### ISSUE TITLE
Create login controller and view

### ISSUE THREAD

**Issue by nerminjukan** [nerminjukan/DiaGenKri#2]

**Comment by nerminjukan** [comment]
After implementing several pages (so it will make sence), we need to initiate the $SESSION parameter after successful login, so we can maintain the state.

**Comment by dejvv** [comment]
Yes, therefore doctors aren't required to enter email and password each time they want't to use application.
In case they're in rush, that could make a difference.

**Comment by nerminjukan** [comment]
Please add the "remember me" checkbox and try to implement the $SESSION parameter so that the app remembers the log in parameters and status. Also change the log in page to be consistent with the page template.

**Comment by nerminjukan** [comment]
In case we decide to implement the 'remember me' functionality, I will reopen this issue.
